optimizer:
    lr: 0.005
image_encoder:
    hidden_dimensions: [16, 32, 64]
    attention: True
pose_encoder:
    hidden_dimensions: [256, 256]
    constant_logvar: True
    activation_type: swish
    attention: True

latent_dimension: 128
beta: 0.1
gamma: 0.1
