optimizer:
    lr: 0.001
    betas: 0.9 0.9
scheduler:
    step_size: 10
    gamma: 0.3
image_encoder:
    hidden_dimensions: [16, 32, 64]
    attention: False
pose_encoder:
    hidden_dimensions: [256, 256]
    constant_logvar: False
    activation_type: swish
    attention: False

pose_distribution: simple
latent_dimension: 20
beta: 0.1
gamma: 0.1
